/* AI for Bioinformatics 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  aibio: {
    label: "AI for Bioinformatics 互動考題",
    label_en: "AI for Bioinformatics Interactive Quiz",
    labels_en: {
      "Part I 基礎篇": "Part I — Foundations",
      "Part II 蛋白質 AI": "Part II — Protein AI",
      "Part III 基因組與單細胞 AI": "Part III — Genomic & Single-Cell AI",
      "Part IV 前沿應用": "Part IV — Frontier Applications",
      "Ch 01：AI × 生資 概論": "Ch 01: AI × Bioinformatics Overview",
      "Ch 02：機器學習基礎": "Ch 02: Machine Learning Basics",
      "Ch 03：深度學習基礎": "Ch 03: Deep Learning Basics",
      "Ch 04：生物序列嵌入": "Ch 04: Biological Sequence Embeddings",
      "Ch 05：蛋白質結構預測": "Ch 05: Protein Structure Prediction",
      "Ch 06：蛋白質從頭設計": "Ch 06: De Novo Protein Design",
      "Ch 07：蛋白-配體交互作用": "Ch 07: Protein–Ligand Interaction",
      "Ch 08：調控基因體 AI": "Ch 08: Regulatory Genomics AI",
      "Ch 09：變異判讀與剪接預測": "Ch 09: Variant Calling & Splicing",
      "Ch 10：單細胞基礎模型": "Ch 10: Single-Cell Foundation Models",
      "Ch 11：AI 驅動藥物發現": "Ch 11: AI-Driven Drug Discovery",
      "Ch 12：生醫大型語言模型": "Ch 12: Biomedical LLMs",
      "Ch 13：生資 AI Agents": "Ch 13: Bioinformatics AI Agents",
      "Ch 14：倫理與最佳實踐": "Ch 14: Ethics & Best Practices"
    },
    subjects: {

      "Part I 基礎篇": {

        "Ch 01：AI × 生資 概論": [
          { type:"single",
            stem:"下列哪一項<strong>不是</strong> 2020-2026 推動 AI×生資的主要驅動力？",
            stem_en:"Which is <strong>NOT</strong> a main driver of the 2020–2026 AI × bioinformatics surge?",
            A:"UK Biobank 等大規模資料釋出", A_en:"Large-scale data releases (UK Biobank, etc.)",
            B:"Transformer 架構跨領域有效", B_en:"Transformer generalizing across domains",
            C:"Sanger 定序技術突然便宜 1000 倍", C_en:"A sudden 1000× drop in Sanger sequencing cost",
            D:"AlphaFold3、ESM3 等大模型開放權重", D_en:"Public weights for AlphaFold 3 and ESM3",
            ans:"C",
            exp:"Sanger 並沒有突然降價；驅動力是 NGS 已經夠便宜 + 模型開源 + 算力充足。",
            exp_en:"Sanger didn't drop further; the drivers are already-cheap NGS + open weights + ample compute." },
          { type:"single",
            stem:"L1 (序列→表徵) 與 L2 (序列→結構/功能) 的核心差別是？",
            stem_en:"Core difference between L1 (sequence→representation) and L2 (sequence→structure/function)?",
            A:"L1 必須使用 Transformer，L2 必須使用 CNN", A_en:"L1 must use Transformers; L2 must use CNNs",
            B:"L1 輸出向量供下游使用；L2 直接輸出生物學上有意義的結構或量化指標", B_en:"L1 outputs vectors for downstream tasks; L2 directly outputs biologically meaningful structures/metrics",
            C:"L1 是監督式，L2 是非監督式", C_en:"L1 is supervised, L2 is unsupervised",
            D:"L1 處理 DNA、L2 處理蛋白", D_en:"L1 handles DNA; L2 handles protein",
            ans:"B",
            exp:"L1 是「特徵抽取」階段，L2 是「應用」階段。架構選擇與是否監督是另一個維度。",
            exp_en:"L1 is feature extraction; L2 is application. Architecture and supervision are orthogonal axes." },
          { type:"single",
            stem:"接到「800 條腫瘤外顯子組篩選致病變異」任務，你應該優先嘗試？",
            stem_en:"Task: prioritize pathogenic variants from 800 tumor exomes. First-line approach?",
            A:"從零訓練一個 Transformer 預測致病性", A_en:"Train a Transformer from scratch",
            B:"先用既有工具 (e.g. AlphaMissense、SpliceAI) + 經典 ML", B_en:"Use existing tools (AlphaMissense, SpliceAI) + classical ML",
            C:"跳過 AI，只用 VEP 注解", C_en:"Skip AI; use VEP only",
            D:"用 LLM 直接讀 VCF 給診斷", D_en:"Feed VCF to an LLM for diagnosis",
            ans:"B",
            exp:"資料量太小不適合從零訓練 DL；最佳實踐是把預訓練大模型當特徵抽取器，再加上輕量分類器。",
            exp_en:"800 samples is too few for from-scratch DL; use pretrained models as feature extractors with a light classifier on top." },
          { type:"single",
            stem:"L4 (Knowledge Synthesis / Agent) 層的代表應用是？",
            stem_en:"Representative application of the L4 (Knowledge Synthesis / Agent) layer?",
            A:"AlphaFold 預測單一蛋白結構", A_en:"Single protein structure with AlphaFold",
            B:"用 LLM 整合文獻、資料庫、工具呼叫產生分析腳本或診斷建議", B_en:"LLMs integrating literature, databases, and tool calls to generate scripts or clinical suggestions",
            C:"Enformer 預測表達量", C_en:"Enformer predicting expression",
            D:"DNABERT 嵌入序列", D_en:"DNABERT embedding sequences",
            ans:"B",
            exp:"L4 強調的是知識合成與 agent 工具呼叫；其他選項屬於 L1/L2 層。",
            exp_en:"L4 emphasizes knowledge synthesis and tool-using agents; the other options are L1/L2." },
          { type:"single",
            stem:"以下何者最能描述 attention 機制在生物序列建模中的角色？",
            stem_en:"Which best describes the role of attention in biological sequence modeling?",
            A:"加快參數初始化速度", A_en:"Speeds up parameter initialization",
            B:"讓模型能同時關注序列上任意兩個位置之間的關係", B_en:"Lets the model relate any two positions in a sequence",
            C:"取代 GPU，降低運算成本", C_en:"Replaces GPUs and reduces compute cost",
            D:"專為非編碼 RNA 設計", D_en:"Specifically designed for ncRNA",
            ans:"B",
            exp:"Attention 的核心是讓任意兩個 token 直接交互，這對長距離 enhancer-promoter 等生物訊號至關重要。",
            exp_en:"Attention enables direct interaction between any two tokens — crucial for long-range biology like enhancer–promoter signals." },
          { type:"multi",
            stem:"下列哪些任務通常會放在 AI×生資的 L2「序列 → 結構/功能」層？（多選）",
            stem_en:"Which tasks typically belong to L2 'sequence → structure/function'? (Multiple)",
            A:"AlphaFold 預測蛋白質 3D 結構", A_en:"AlphaFold predicting 3D protein structure",
            B:"Enformer 預測表達量軌跡", B_en:"Enformer predicting expression tracks",
            C:"DNABERT 把序列編成向量", C_en:"DNABERT encoding sequences into vectors",
            D:"SpliceAI 預測剪接位點機率", D_en:"SpliceAI predicting splice probabilities",
            ans:["A","B","D"],
            exp:"A、B、D 都直接從序列輸出生物意義量化指標；C 屬於 L1 表徵層。",
            exp_en:"A, B, D directly output biological quantities from sequence; C belongs to L1 (representations)." },
          { type:"tf",
            stem:"是非題：fine-tune 預訓練模型通常比從零訓練在中小型資料集表現更好。",
            stem_en:"True/False: Fine-tuning a pretrained model generally beats training from scratch on small/medium datasets.",
            ans:"T",
            exp:"小資料無法支持大型模型從零訓練；fine-tune 已成現代生資 AI 標準做法。",
            exp_en:"Small data can't support training a large model from scratch; fine-tuning is now the standard." },
          { type:"tf",
            stem:"是非題：所有 AI 模型都應追求最複雜的架構以達到最佳表現。",
            stem_en:"True/False: One should always pick the most complex architecture for best performance.",
            ans:"F",
            exp:"任務簡單或資料量小，經典 ML 往往勝過深層模型；應依任務選工具。",
            exp_en:"For simple tasks or small data, classical ML often beats deep models. Pick tools by task fit." }
        ],

        "Ch 02：機器學習基礎": [
          { type:"single",
            stem:"罕見疾病資料 (1:200 不平衡)，AUROC=0.95 但 AUPRC=0.20。最合理的解讀？",
            stem_en:"Rare disease classifier (1:200), AUROC=0.95 but AUPRC=0.20. Best interpretation?",
            A:"模型表現極佳", A_en:"Excellent model",
            B:"排序能力 OK，但實際應用 precision 仍很低，誤報率高", B_en:"Ranking is OK but precision in deployment is low — many false positives",
            C:"資料一定有 bug", C_en:"Data must be buggy",
            D:"AUPRC 沒有意義可忽略", D_en:"Ignore AUPRC, it's meaningless",
            ans:"B",
            exp:"在 1:200 場景中 AUPRC 0.20 雖比 baseline 0.005 高很多，但仍代表 ~80% 預測陽性是錯的。",
            exp_en:"At 1:200 base rate, AUPRC 0.20 is far above baseline 0.005, but still ~80% of predicted positives are false alarms." },
          { type:"single",
            stem:"哪一種切分最容易導致「假好」表現？",
            stem_en:"Which split most likely creates artificially inflated metrics?",
            A:"對病人 ID 做 group K-fold", A_en:"Group K-fold by patient ID",
            B:"隨機 split — 同一病人在 train 與 test 各出現一次", B_en:"Random split where the same patient appears in both train and test",
            C:"序列相似度 30% 切分", C_en:"Sequence-identity split at 30%",
            D:"Stratified K-fold", D_en:"Stratified K-fold",
            ans:"B",
            exp:"病人重疊是常見的 leakage 來源；正確做法是 group K-fold。",
            exp_en:"Patient overlap is a classic leakage source; correct fix is group K-fold." },
          { type:"single",
            stem:"自監督式 (self-supervised) 模型最大的優勢是？",
            stem_en:"Biggest advantage of self-supervised models?",
            A:"不需要算力", A_en:"No compute required",
            B:"可以利用海量無標籤序列預訓練，再用小量標籤資料 fine-tune", B_en:"Can pretrain on massive unlabeled data and fine-tune with little labeled data",
            C:"永遠比監督式準", C_en:"Always beats supervised",
            D:"不需要驗證集", D_en:"No validation set needed",
            ans:"B",
            exp:"所有現代生物 foundation model（ESM、scGPT、Evo 2）都採此設計。",
            exp_en:"All modern bio foundation models (ESM, scGPT, Evo 2) use this recipe." },
          { type:"single",
            stem:"關於 train / validation / test 切分，下列何者正確？",
            stem_en:"Which is correct about train/val/test splits?",
            A:"validation 集可用於報告最終表現", A_en:"Final performance can be reported from the validation set",
            B:"test 集只應在最終評估時看一次，不參與超參數選擇", B_en:"Test set is held out and used only once at final evaluation",
            C:"train 集用於選擇超參數", C_en:"Training set is used for hyperparameter selection",
            D:"三者完全可以重疊", D_en:"All three can overlap",
            ans:"B",
            exp:"test 必須完全隔離；val 用於選超參數；train 用於擬合參數。",
            exp_en:"Test is fully held out; val tunes hyperparameters; train fits parameters." },
          { type:"single",
            stem:"對 1k–100k 的 tabular 任務，2026 年的「king」是？",
            stem_en:"For 1k–100k tabular tasks in 2026, the 'king' algorithm is?",
            A:"Naive Bayes", A_en:"Naive Bayes",
            B:"XGBoost / LightGBM 等 GBM", B_en:"XGBoost / LightGBM (gradient-boosted trees)",
            C:"最近鄰", C_en:"k-NN",
            D:"Logistic regression", D_en:"Logistic regression",
            ans:"B",
            exp:"GBM 在 1k–100k tabular 範疇仍是最強通用 baseline，常配 SHAP 做特徵解釋。",
            exp_en:"GBMs remain the strongest general baseline at this scale, often paired with SHAP." },
          { type:"single",
            stem:"類別嚴重不平衡 (1:50+) 時，最該追加的指標是？",
            stem_en:"Under heavy class imbalance (≥1:50), which metric must you add?",
            A:"Accuracy", A_en:"Accuracy",
            B:"AUPRC（PR 曲線下面積）", B_en:"AUPRC (area under PR curve)",
            C:"R²", C_en:"R²",
            D:"Mean squared error", D_en:"Mean squared error",
            ans:"B",
            exp:"AUROC 在不平衡時會偏樂觀；AUPRC + MCC 更能反映實際 deployment 行為。",
            exp_en:"AUROC is over-optimistic under imbalance; AUPRC and MCC better reflect deployment behavior." },
          { type:"multi",
            stem:"下列哪些是常見的 data leakage 來源？（多選）",
            stem_en:"Which are common data leakage sources? (Multiple)",
            A:"同一病人多筆樣本同時出現在 train 與 test", A_en:"Same patient appearing in train and test",
            B:"訓練集標準化參數應用到測試集", B_en:"Applying training normalization stats to test (correct usage)",
            C:"同一基因家族同源序列分散到不同 fold", C_en:"Homologous sequences split across folds",
            D:"用 future timestamp 的資料訓練 past task", D_en:"Training on future-timestamp data for a past task",
            ans:["A","C","D"],
            exp:"B 是正確做法不算 leakage；A、C、D 都是真正的 leakage 場景。",
            exp_en:"B is correct practice (not leakage). A, C, D are real leakage failure modes." },
          { type:"multi",
            stem:"下列哪些情況應優先嘗試經典 ML 而非深度學習？（多選）",
            stem_en:"When should classical ML be preferred over DL? (Multiple)",
            A:"資料量 < 1000 筆", A_en:"Dataset < 1000 samples",
            B:"要求高度可解釋性的臨床決策", B_en:"Highly interpretable clinical decision",
            C:"輸入是 100 萬條 DNA 序列", C_en:"Input is 1M DNA sequences",
            D:"特徵已是工程整理好的數值表格", D_en:"Features already in clean numeric tabular form",
            ans:["A","B","D"],
            exp:"小資料、需要可解釋、tabular 都是經典 ML 的甜蜜點；C 屬於序列 DL 強項。",
            exp_en:"Small data, interpretability, and tabular features are classical ML's sweet spots; C favors sequence DL." },
          { type:"tf",
            stem:"是非題：監督式學習一定比非監督式學習效果好。",
            stem_en:"True/False: Supervised learning is always better than unsupervised.",
            ans:"F",
            exp:"取決於任務與標籤可得性。許多探索性任務 (e.g. 細胞分群) 無監督是首選。",
            exp_en:"Depends on task and label availability. For exploratory tasks (e.g., cell clustering), unsupervised is the right choice." },
          { type:"tf",
            stem:"是非題：序列任務的訓練/測試切分應確保兩集合間序列相似度低於某個閾值（如 30% identity）。",
            stem_en:"True/False: For sequence tasks, train/test splits should keep cross-set sequence identity below a threshold (e.g., 30%).",
            ans:"T",
            exp:"sequence-identity split 是常用做法，避免模型靠記憶相似序列「作弊」。",
            exp_en:"Sequence-identity splits prevent the model from memorizing similar sequences." }
        ],

        "Ch 03：深度學習基礎": [
          { type:"single",
            stem:"為什麼現代 Transformer 在生物序列任務全面取代 RNN？",
            stem_en:"Why have Transformers replaced RNNs in modern bio-sequence tasks?",
            A:"Transformer 參數比較少", A_en:"Transformers have fewer parameters",
            B:"Attention 可平行運算且能直接捕捉長距離依賴", B_en:"Attention parallelizes and directly captures long-range dependencies",
            C:"RNN 已被禁用", C_en:"RNNs are deprecated by law",
            D:"Transformer 不需要 GPU", D_en:"Transformers don't need GPUs",
            ans:"B",
            exp:"長距離依賴（如 enhancer-promoter 100 kb）是生物序列關鍵，Transformer 一步即可關聯。",
            exp_en:"Long-range dependencies (e.g., 100 kb enhancer–promoter) are central to biology; Transformers relate them in one step." },
          { type:"single",
            stem:"訓練 loss 從第一個 epoch 就 NaN，最可能的原因？",
            stem_en:"Loss is NaN from epoch 1. Most likely cause?",
            A:"模型太深", A_en:"Model too deep",
            B:"learning rate 太大、輸入未正規化、log(0) 等數值問題", B_en:"LR too high, unnormalized inputs, or log(0) numerical issues",
            C:"batch size 太小", C_en:"Batch size too small",
            D:"一定是資料 bug", D_en:"Must be a data bug",
            ans:"B",
            exp:"先降 LR、檢查輸入分佈、加 gradient clipping。",
            exp_en:"Lower LR, check input distribution, add gradient clipping." },
          { type:"single",
            stem:"5,000 條 DNA 序列分類 enhancer，最佳策略？",
            stem_en:"5,000 DNA sequences, enhancer classification — best strategy?",
            A:"從零訓練 100M 參數 Transformer", A_en:"Train a 100M-param Transformer from scratch",
            B:"Fine-tune 預訓練的 DNABERT 或 Nucleotide Transformer", B_en:"Fine-tune pretrained DNABERT or Nucleotide Transformer",
            C:"必須用 ResNet50", C_en:"Must use ResNet50",
            D:"只用統計方法", D_en:"Classical statistics only",
            ans:"B",
            exp:"小規模資料用 fine-tune；通常 1 小時跑完且勝過 from-scratch。",
            exp_en:"Fine-tuning is the right move for small datasets — typically finishes in an hour and beats from-scratch." },
          { type:"single",
            stem:"DNA 序列做 1D-CNN 時，標準輸入格式是？",
            stem_en:"Standard 1D-CNN input format for DNA sequences?",
            A:"(batch, length, 4) — channels-last", A_en:"(batch, length, 4) — channels-last",
            B:"(batch, 4, length) — channels-first", B_en:"(batch, 4, length) — channels-first",
            C:"(length, 4)", C_en:"(length, 4)",
            D:"(batch, length, length, 4)", D_en:"(batch, length, length, 4)",
            ans:"B",
            exp:"PyTorch / 大多數 1D-CNN 採用 channels-first；4 channels = A,C,G,T。",
            exp_en:"PyTorch and most 1D-CNNs use channels-first; 4 channels are A,C,G,T." },
          { type:"single",
            stem:"GPU 記憶體耗光時，正確的優先順序為？",
            stem_en:"OOM on GPU — correct priority order?",
            A:"先縮 batch → mixed precision → gradient accumulation", A_en:"Shrink batch → mixed precision → gradient accumulation",
            B:"先 mixed precision → gradient accumulation → 最後才縮 batch", B_en:"Mixed precision → gradient accumulation → shrink batch as last resort",
            C:"換 CPU", C_en:"Switch to CPU",
            D:"用更大的 batch size", D_en:"Use a bigger batch size",
            ans:"B",
            exp:"先用便宜手段：bf16/fp16、grad accum；最後才縮 effective batch（因為小 batch 影響 BatchNorm 與收斂）。",
            exp_en:"Try cheap tricks first (bf16/fp16, grad accum); reduce effective batch only as last resort (it hurts BN and convergence)." },
          { type:"single",
            stem:"以下哪一個激活函數是 2026 年 Transformer 主流選擇？",
            stem_en:"Which activation is the de facto choice in modern Transformers (2026)?",
            A:"Sigmoid", A_en:"Sigmoid",
            B:"Tanh", B_en:"Tanh",
            C:"GELU / SiLU", C_en:"GELU / SiLU",
            D:"Step function", D_en:"Step function",
            ans:"C",
            exp:"GPT、ESM、AlphaFold 等普遍採用 GELU/SiLU；比 ReLU 平滑、收斂更快。",
            exp_en:"GPT, ESM, and AlphaFold all use GELU/SiLU — smoother and converging faster than ReLU." },
          { type:"multi",
            stem:"下列哪些是訓練 DL 的常見保命招數？（多選）",
            stem_en:"Which are sane survival tips when training DL? (Multiple)",
            A:"先用 mini-batch overfit 確認 pipeline", A_en:"Overfit a mini-batch first to verify the pipeline",
            B:"用 LR finder 掃 1e-7 到 1e-1", B_en:"Use an LR finder sweeping 1e-7 to 1e-1",
            C:"固定所有 random seed", C_en:"Pin all random seeds",
            D:"從第一天就訓練 100M 參數模型", D_en:"Start by training a 100M-param model on day one",
            ans:["A","B","C"],
            exp:"D 是反模式；前三項是專業 DL 訓練的標準動作。",
            exp_en:"D is an anti-pattern; the first three are standard professional practice." },
          { type:"multi",
            stem:"下列哪些屬於正則化技巧？（多選）",
            stem_en:"Which are regularization techniques? (Multiple)",
            A:"Dropout", A_en:"Dropout",
            B:"Weight decay", B_en:"Weight decay",
            C:"Early stopping", C_en:"Early stopping",
            D:"Larger learning rate", D_en:"Larger learning rate",
            ans:["A","B","C"],
            exp:"前三項都是常用的反過擬合手段；提高 LR 並不是正則化。",
            exp_en:"The first three combat overfitting; raising LR is not regularization." },
          { type:"tf",
            stem:"是非題：CNN 看「局部」、RNN 看「順序」、Transformer 看「全局」。",
            stem_en:"True/False: CNNs see local, RNNs see sequential, Transformers see global.",
            ans:"T",
            exp:"這是三大架構直覺最簡明的記憶口訣。",
            exp_en:"A clean mnemonic for the three architectural styles." },
          { type:"tf",
            stem:"是非題：one-hot DNA 應該寫成 A=[1,0,0,0]、N=[0.25,0.25,0.25,0.25]。",
            stem_en:"True/False: One-hot DNA should encode A=[1,0,0,0], N=[0.25,0.25,0.25,0.25].",
            ans:"T",
            exp:"N 用均勻分佈是最常見的「未知」處理。",
            exp_en:"Uniform 0.25 is the standard handling of N (unknown bases)." }
        ],

        "Ch 04：生物序列嵌入": [
          { type:"single",
            stem:"一個「好」的序列嵌入空間，最重要的性質是？",
            stem_en:"Most important property of a good embedding space?",
            A:"維度越高越好", A_en:"Higher dimensions are better",
            B:"功能相似的序列在空間中距離也相近", B_en:"Functionally similar sequences are close",
            C:"每一維都有明確生物學意義", C_en:"Each dimension has explicit biological meaning",
            D:"必須是整數", D_en:"Must be integers",
            ans:"B",
            exp:"重點是「相對距離」有意義；個別維度通常沒有單一生物意涵。",
            exp_en:"What matters is relative distance, not the meaning of single dimensions." },
          { type:"single",
            stem:"600bp 的人類啟動子序列，2026 年最佳 baseline 嵌入模型？",
            stem_en:"Best 2026 baseline embedder for a 600 bp human promoter?",
            A:"word2vec 訓練的 dna2vec", A_en:"dna2vec from word2vec",
            B:"DNABERT-2 或 Nucleotide Transformer", B_en:"DNABERT-2 or Nucleotide Transformer",
            C:"Evo 2 40B", C_en:"Evo 2 40B",
            D:"one-hot 即可", D_en:"One-hot suffices",
            ans:"B",
            exp:"500M 級模型對 600bp 任務通常足夠且運算成本低。",
            exp_en:"500M-class models are plenty for 600bp tasks and cheap to run." },
          { type:"single",
            stem:"想做「語意 BLAST」(用 embedding 檢索功能相似蛋白)，最適合的工具？",
            stem_en:"For 'semantic BLAST' via embeddings, the right toolchain is?",
            A:"暴力比對全 UniProt", A_en:"Brute-force all UniProt",
            B:"ESM 嵌入 + FAISS / ScaNN 索引", B_en:"ESM embeddings + FAISS / ScaNN index",
            C:"必須用 BLAST，AI 沒用", C_en:"Must use BLAST; AI doesn't help",
            D:"Excel 排序", D_en:"Excel sort",
            ans:"B",
            exp:"FAISS / ScaNN 可在百億向量上做秒級 ANN 檢索，是現代「語意檢索」標配。",
            exp_en:"FAISS/ScaNN scale to ~10B vectors with sub-second ANN — the standard for semantic retrieval." },
          { type:"single",
            stem:"對 100kb-1Mb 的長序列，2026 年最常用的嵌入模型族？",
            stem_en:"For 100kb–1Mb long sequences, the typical 2026 embedder family is?",
            A:"DNABERT-2", A_en:"DNABERT-2",
            B:"HyenaDNA / Evo 2 等長上下文模型", B_en:"HyenaDNA / Evo 2 — long-context models",
            C:"k-mer counter", C_en:"k-mer counters",
            D:"BERT-tiny", D_en:"BERT-tiny",
            ans:"B",
            exp:"O(L²) attention 在 1M token 不可行；需要 Hyena / state-space / linear attention 等架構。",
            exp_en:"O(L²) attention is intractable at 1M tokens; need Hyena / state-space / linear attention." },
          { type:"single",
            stem:"ESM-2 對長度 L 蛋白質輸出 (L, D)，要做整條序列分類，常見作法？",
            stem_en:"ESM-2 outputs (L, D) for a length-L protein. To classify the whole sequence, the common practice is?",
            A:"取第一個位置的向量", A_en:"Take the first-position vector",
            B:"對 L 維度做 mean pooling 得到 (D,) 向量", B_en:"Mean-pool over L → (D,) vector",
            C:"求所有元素總和", C_en:"Sum every element",
            D:"取最大值", D_en:"Take the global max",
            ans:"B",
            exp:"mean pooling 是最常見的序列級向量化方式；CLS token 也常用但需要額外標準化。",
            exp_en:"Mean pooling is the most common sequence-level pooling; CLS works too but needs additional normalization." },
          { type:"single",
            stem:"Evo 2 與 ESM-2 的關鍵不同？",
            stem_en:"Key difference between Evo 2 and ESM-2?",
            A:"Evo 2 是蛋白模型，ESM-2 是 DNA 模型", A_en:"Evo 2 is a protein model and ESM-2 is a DNA model",
            B:"Evo 2 跨 DNA/RNA/蛋白且支援 1M 上下文；ESM-2 專注於蛋白", B_en:"Evo 2 spans DNA/RNA/protein with 1M context; ESM-2 focuses on protein",
            C:"兩者完全相同", C_en:"They are identical",
            D:"Evo 2 不能用 fine-tune", D_en:"Evo 2 can't be fine-tuned",
            ans:"B",
            exp:"Evo 2 是跨域基因組大模型；ESM 系列專為蛋白質設計。",
            exp_en:"Evo 2 is a cross-domain genomic LM; ESM is protein-specific." },
          { type:"multi",
            stem:"下列哪些屬於「Transformer foundation model」世代的序列嵌入？（多選）",
            stem_en:"Which belong to the Transformer foundation model generation? (Multiple)",
            A:"ESM-2 / ESM-3", A_en:"ESM-2 / ESM-3",
            B:"DNABERT-2", B_en:"DNABERT-2",
            C:"Nucleotide Transformer", C_en:"Nucleotide Transformer",
            D:"k-mer counts", D_en:"k-mer counts",
            ans:["A","B","C"],
            exp:"k-mer 屬於第一代 hand-crafted 特徵；其餘都是 Transformer 基礎模型。",
            exp_en:"k-mers are first-gen hand-crafted features; the rest are Transformer foundation models." },
          { type:"multi",
            stem:"以下哪些是常見的「整段序列向量化」方法？（多選）",
            stem_en:"Which are common ways to pool an embedding to a single vector? (Multiple)",
            A:"mean pooling", A_en:"Mean pooling",
            B:"取 [CLS] / [SEP] token 向量", B_en:"Take [CLS] / [SEP] token vector",
            C:"max pooling", C_en:"Max pooling",
            D:"隨機取一個位置", D_en:"Pick a random position",
            ans:["A","B","C"],
            exp:"D 不穩定且非標準；前三項都是常見方法，依任務而異。",
            exp_en:"D is non-standard and unstable. The first three are all common, choice depends on task." },
          { type:"tf",
            stem:"是非題：FAISS 等向量資料庫無法處理百萬級以上的向量檢索。",
            stem_en:"True/False: FAISS-style vector DBs can't handle million-scale retrieval.",
            ans:"F",
            exp:"FAISS / ScaNN / Qdrant 等都能處理百萬到百億級向量。",
            exp_en:"FAISS / ScaNN / Qdrant scale from millions to billions of vectors." },
          { type:"tf",
            stem:"是非題：embedding 空間中個別維度通常沒有單一生物學意義。",
            stem_en:"True/False: Individual dimensions of an embedding usually have no single biological meaning.",
            ans:"T",
            exp:"重要的是相對距離與方向，而非單一座標。",
            exp_en:"What matters is relative distance and direction, not single coordinate values." }
        ]
      },

      "Part II 蛋白質 AI": {

        "Ch 05：蛋白質結構預測": [
          { type:"single",
            stem:"AlphaFold 3 相對於 AlphaFold 2 最關鍵的突破是？",
            stem_en:"AlphaFold 3's most important breakthrough vs AlphaFold 2?",
            A:"蛋白質單體精度大幅提升", A_en:"Big jump in monomer accuracy",
            B:"用擴散模組支援任意分子（蛋白+DNA/RNA+配體+離子）的複合物", B_en:"Diffusion module supports arbitrary molecule complexes (protein + DNA/RNA + ligand + ion)",
            C:"不再需要序列輸入", C_en:"No sequence input needed",
            D:"改用 RNN 架構", D_en:"Switched to RNN",
            ans:"B",
            exp:"AF3 用 diffusion 對所有原子一視同仁，因此天然支援任意分子複合物。",
            exp_en:"AF3's diffusion treats all atoms uniformly, naturally supporting any molecular complex." },
          { type:"single",
            stem:"AlphaFold 結果中 pLDDT &lt; 50 的橘色區段，最可能代表？",
            stem_en:"An AlphaFold region with pLDDT < 50 (orange) most likely represents?",
            A:"最自信的折疊核心", A_en:"The most confident folded core",
            B:"內在無序區 (IDR) 或預測失敗", B_en:"Intrinsically disordered region or prediction failure",
            C:"結合位點", C_en:"Binding site",
            D:"螺旋結構", D_en:"Alpha helix",
            ans:"B",
            exp:"低 pLDDT 通常是 IDR 或 thin MSA；不該直接用做下游分析。",
            exp_en:"Low pLDDT usually means IDRs or thin MSAs; not for downstream use." },
          { type:"single",
            stem:"快速預測 10 萬條沒有同源序列的蛋白結構，最合適的工具？",
            stem_en:"Best tool for predicting 100K proteins with no homologs?",
            A:"AlphaFold 2 全 MSA 流程", A_en:"AlphaFold 2 with full MSA",
            B:"ESMFold（無 MSA、~60× 快）", B_en:"ESMFold (no MSA, ~60× faster)",
            C:"經典 Rosetta ab initio", C_en:"Classic Rosetta ab initio",
            D:"X-ray 結晶", D_en:"X-ray crystallography",
            ans:"B",
            exp:"無 MSA 場景 ESMFold 最佳實務；精度略低 (~85 GDT) 但極快。",
            exp_en:"For no-MSA scenarios ESMFold is best practice — slightly lower accuracy (~85 GDT) but very fast." },
          { type:"single",
            stem:"看到 AlphaFold-Multimer 結果評估 interface 品質的關鍵指標是？",
            stem_en:"The key metric for interface quality in AlphaFold-Multimer is?",
            A:"pLDDT", A_en:"pLDDT",
            B:"ipTM (interface predicted TM-score)", B_en:"ipTM (interface predicted TM-score)",
            C:"GC content", C_en:"GC content",
            D:"序列長度", D_en:"Sequence length",
            ans:"B",
            exp:"ipTM 評估介面置信度；&gt; 0.8 才算可信，pLDDT 反映個別殘基。",
            exp_en:"ipTM scores interface confidence; > 0.8 is trusted. pLDDT reflects per-residue confidence." },
          { type:"single",
            stem:"AlphaFold 對單點突變的影響預測，下列敘述最準確？",
            stem_en:"AlphaFold's behavior under single-point mutations?",
            A:"極為敏感，可預測 ΔΔG", A_en:"Extremely sensitive; predicts ΔΔG",
            B:"通常對單點突變的結構變化不敏感；應改用 AlphaMissense / ESM-1v 或 free-energy 模擬", B_en:"Usually insensitive; use AlphaMissense / ESM-1v or free-energy simulations instead",
            C:"完全無法處理任何突變", C_en:"Can't handle any mutation",
            D:"只看胺基酸電荷", D_en:"Only looks at residue charge",
            ans:"B",
            exp:"AF2/3 主要學習序列家族特徵；單點變化通常不會大幅改變預測。",
            exp_en:"AF2/3 learn family-level features; single-point changes rarely shift predictions much." },
          { type:"single",
            stem:"CASP 14 (2020) AlphaFold 2 平均 GDT-TS 約為？",
            stem_en:"AlphaFold 2's average GDT-TS at CASP14 (2020) was approximately?",
            A:"30 分", A_en:"~30",
            B:"60 分", B_en:"~60",
            C:"92 分（接近實驗等級）", C_en:"~92 (experimental level)",
            D:"100 分", D_en:"100",
            ans:"C",
            exp:"AF2 在 CASP14 達 ~92 GDT-TS，被認為將蛋白折疊問題大致解決。",
            exp_en:"AF2 reached ~92 GDT-TS at CASP14, which the field considers as largely solving folding." },
          { type:"multi",
            stem:"下列哪些情境 AlphaFold 容易表現不佳？（多選）",
            stem_en:"In which situations is AlphaFold likely to underperform? (Multiple)",
            A:"內在無序蛋白 (IDR)", A_en:"Intrinsically disordered proteins",
            B:"離子通道的 active/inactive 雙態", B_en:"Active/inactive states of ion channels",
            C:"完全結構化的酵素核心", C_en:"Fully structured enzyme core",
            D:"條件相依結構（pH、磷酸化變化）", D_en:"Condition-dependent conformations (pH, phosphorylation)",
            ans:["A","B","D"],
            exp:"C 是 AlphaFold 的甜蜜點；其餘三項是已知弱點。",
            exp_en:"C is AlphaFold's sweet spot; the others are known weaknesses." },
          { type:"multi",
            stem:"哪些指標可以一起評估 AlphaFold 預測的整體可信度？（多選）",
            stem_en:"Which metrics together evaluate an AlphaFold prediction's overall reliability? (Multiple)",
            A:"pLDDT", A_en:"pLDDT",
            B:"PAE (predicted aligned error)", B_en:"PAE (predicted aligned error)",
            C:"ipTM", C_en:"ipTM",
            D:"序列長度", D_en:"Sequence length",
            ans:["A","B","C"],
            exp:"D 與品質無關；前三者組合是 AlphaFold 結果的標準解讀方式。",
            exp_en:"D is irrelevant; the first three are the standard set." },
          { type:"tf",
            stem:"是非題：把整個結構平均成一個 pLDDT 數字是浪費資訊的做法。",
            stem_en:"True/False: Averaging pLDDT to one number throws away the per-residue signal.",
            ans:"T",
            exp:"應逐殘基檢查；不同區段可信度差異很大。",
            exp_en:"Inspect per-residue; per-region confidence varies greatly." },
          { type:"tf",
            stem:"是非題：AlphaFold 3 在訓練分佈外 (OOD) 標靶仍可能產生不合理 pose。",
            stem_en:"True/False: AlphaFold 3 can still hallucinate non-physical poses on OOD targets.",
            ans:"T",
            exp:"獨立 benchmark 顯示 AF3 對新化學家族仍會 hallucinate；推薦過 PoseBusters。",
            exp_en:"Independent benchmarks confirm AF3 hallucinates on novel chemotypes; PoseBusters check is recommended." }
        ],

        "Ch 06：蛋白質從頭設計": [
          { type:"single",
            stem:"RFdiffusion 與 ProteinMPNN 在 design pipeline 中的角色是？",
            stem_en:"Roles of RFdiffusion and ProteinMPNN in design pipelines?",
            A:"兩者都是序列設計工具", A_en:"Both design sequences",
            B:"RFdiffusion 生成 3D 骨架；ProteinMPNN 為骨架選胺基酸", B_en:"RFdiffusion generates 3D backbones; ProteinMPNN picks amino acids for the backbone",
            C:"兩者都是 AlphaFold 替代品", C_en:"Both replace AlphaFold",
            D:"RFdiffusion 訓練 ProteinMPNN", D_en:"RFdiffusion trains ProteinMPNN",
            ans:"B",
            exp:"backbone → sequence → validate (AlphaFold) 是現代 de novo 設計的三段式流程。",
            exp_en:"backbone → sequence → validate (AlphaFold) is the canonical three-stage de novo pipeline." },
          { type:"single",
            stem:"AlphaFold「self-consistency」檢查在設計中是指？",
            stem_en:"What is AlphaFold 'self-consistency' in design?",
            A:"AlphaFold 重複預測同一序列", A_en:"Predicting the same sequence twice",
            B:"把 ProteinMPNN 設計的序列丟回 AF 重新折疊，看是否回到目標 backbone", B_en:"Feeding the designed sequence back to AF and checking if it folds to the target backbone",
            C:"AlphaFold 自我計算 confidence", C_en:"AF auto-computes confidence",
            D:"兩個 AF 模型結果相似", D_en:"Two AF models agree",
            ans:"B",
            exp:"in silico 自洽：pLDDT &gt; 80 + RMSD &lt; 2Å 才會送 wet lab。",
            exp_en:"In silico self-consistency: only pLDDT > 80 + RMSD < 2Å designs go to the wet lab." },
          { type:"single",
            stem:"即使 AlphaFold 顯示完美 self-consistency，實驗仍可能失敗，最常見原因？",
            stem_en:"Even with perfect AF self-consistency, experiments can fail. Why?",
            A:"AlphaFold 都是錯的", A_en:"AlphaFold is always wrong",
            B:"設計序列可能溶解度差、表達低、或在多種其他構象都穩定", B_en:"The sequence may be insoluble, hard to express, or stable in many conformations",
            C:"設計太多", C_en:"Too many designs",
            D:"RFdiffusion 不支援", D_en:"RFdiffusion doesn't support it",
            ans:"B",
            exp:"in silico OK 不等於 in vitro OK；表達性、溶解度、聚集都可能失敗。",
            exp_en:"In silico OK ≠ in vitro OK; expressibility, solubility, aggregation all matter." },
          { type:"single",
            stem:"想設計能結合特定標靶 hotspot 的小分子蛋白 (binder)，最常用的條件式生成？",
            stem_en:"To design a mini-protein binder against a target hotspot, the most common conditional generation is?",
            A:"RFdiffusion 帶 ppi.hotspot_res 條件", A_en:"RFdiffusion with ppi.hotspot_res conditioning",
            B:"純隨機生成", B_en:"Pure random generation",
            C:"BLAST", C_en:"BLAST",
            D:"Rosetta only", D_en:"Rosetta only",
            ans:"A",
            exp:"RFdiffusion 對 hotspot 的條件控制是 binder design 業界標準。",
            exp_en:"RFdiffusion's hotspot conditioning is the industry standard for binder design." },
          { type:"single",
            stem:"ProteinMPNN 採用什麼方法為骨架選擇胺基酸？",
            stem_en:"How does ProteinMPNN pick amino acids for a backbone?",
            A:"純隨機", A_en:"Pure random",
            B:"Message-passing 神經網路（GNN-like）", B_en:"Message-passing neural network (GNN-like)",
            C:"Rosetta 經驗能量函數", C_en:"Rosetta empirical energy function",
            D:"BLAST", D_en:"BLAST",
            ans:"B",
            exp:"ProteinMPNN 是 message-passing GNN，效率與成功率都優於物理 Rosetta。",
            exp_en:"ProteinMPNN is a message-passing GNN; efficiency and success rate exceed physics-based Rosetta." },
          { type:"single",
            stem:"ProteinMPNN 的實驗成功率 (~52%) 較傳統 Rosetta (~10%) 高很多，主要原因？",
            stem_en:"Why does ProteinMPNN reach ~52% experimental success vs ~10% for classic Rosetta?",
            A:"它使用更強的物理力場", A_en:"Stronger physics force field",
            B:"從大量實驗驗證的真實序列-結構對學習，避開人造能量函數誤差", B_en:"Learns from real experimentally-validated sequence-structure pairs, avoiding hand-crafted energy errors",
            C:"它不檢查胺基酸合法性", C_en:"It doesn't check residue legality",
            D:"它直接從 NCBI 抓序列", D_en:"It fetches sequences from NCBI",
            ans:"B",
            exp:"data-driven 學習能捕捉物理函數捕捉不到的微妙模式。",
            exp_en:"Data-driven learning captures patterns hand-crafted energies miss." },
          { type:"multi",
            stem:"下列哪些是 RFdiffusion + ProteinMPNN 已成功的應用？（多選）",
            stem_en:"Which are demonstrated success cases of RFdiffusion + ProteinMPNN? (Multiple)",
            A:"SARS-CoV-2 spike 中和 binder", A_en:"SARS-CoV-2 spike neutralizing binders",
            B:"對稱奈米粒子顯示抗原", B_en:"Symmetric nanoparticles displaying antigens",
            C:"Antibody CDR 設計（RFdiffusion-Ab）", C_en:"Antibody CDR design (RFdiffusion-Ab)",
            D:"RNA 全基因組生成", D_en:"Whole-genome RNA generation",
            ans:["A","B","C"],
            exp:"D 是基因體 LM (Evo 2) 領域，不是蛋白設計流程。",
            exp_en:"D belongs to genome LMs (Evo 2), not protein design pipelines." },
          { type:"multi",
            stem:"以下哪些是設計者常見的坑？（多選）",
            stem_en:"Common pitfalls for designers? (Multiple)",
            A:"以為 AF self-consistency 高就一定實驗成功", A_en:"Assuming high AF self-consistency guarantees experimental success",
            B:"忽略表達性與溶解度", B_en:"Ignoring expressibility and solubility",
            C:"沒有大量平行設計後篩選", C_en:"Not running 1000+ designs and filtering",
            D:"用 PyMOL 視覺化結構", D_en:"Visualizing structures in PyMOL",
            ans:["A","B","C"],
            exp:"D 是好習慣不是坑；前三項是業界常見錯誤。",
            exp_en:"D is good practice. The first three are common industry mistakes." },
          { type:"tf",
            stem:"是非題：David Baker 的實驗室於 2024 年共獲諾貝爾化學獎，貢獻包含 RFdiffusion / ProteinMPNN 系列工具。",
            stem_en:"True/False: David Baker shared the 2024 Nobel Chemistry Prize for contributions including RFdiffusion / ProteinMPNN.",
            ans:"T",
            exp:"Baker 與 DeepMind Hassabis、Jumper 共獲 2024 年諾貝爾化學獎。",
            exp_en:"Baker shared the 2024 Nobel with DeepMind's Hassabis and Jumper." },
          { type:"tf",
            stem:"是非題：RFdiffusion 是基於 RoseTTAFold 改裝為 diffusion model 的生成式工具。",
            stem_en:"True/False: RFdiffusion is built by adapting RoseTTAFold into a diffusion-based generative model.",
            ans:"T",
            exp:"RFdiffusion 借用 RoseTTAFold 的結構表示與訓練權重，加上去噪過程實現生成。",
            exp_en:"RFdiffusion reuses RoseTTAFold's structure representation and weights, with diffusion denoising added." }
        ],

        "Ch 07：蛋白-配體交互作用": [
          { type:"single",
            stem:"DiffDock 在 PDBBind 上 top-1 success rate 比 AutoDock Vina 高近 2 倍，但實務上常被 hybrid 取代，主因？",
            stem_en:"DiffDock nearly doubles AutoDock Vina's top-1 on PDBBind, yet hybrid pipelines often replace it. Why?",
            A:"DiffDock 速度太慢", A_en:"DiffDock is too slow",
            B:"DiffDock 對訓練分佈外的標靶或化學家族表現會明顯下降", B_en:"DiffDock degrades on targets/chemotypes outside its training distribution",
            C:"DiffDock 不能輸出 SDF", C_en:"DiffDock can't output SDF",
            D:"DiffDock 還沒開源", D_en:"DiffDock isn't open-source",
            ans:"B",
            exp:"OOD 是生成式 docking 的根本問題，因此 hybrid + 物理 rescore 是 2026 業界共識。",
            exp_en:"OOD is the fundamental issue with generative docking; hybrid + physics rescoring is the 2026 industry consensus." },
          { type:"single",
            stem:"PoseBusters 的角色是？",
            stem_en:"What is PoseBusters for?",
            A:"全新 docking 演算法", A_en:"A new docking algorithm",
            B:"物理可行性檢查工具，剔除鍵長/角度/碰撞不合理的 pose", B_en:"Physics sanity-check tool that filters poses with unreasonable bond lengths, angles, clashes",
            C:"pose 視覺化軟體", C_en:"A pose viewer",
            D:"親和力預測模型", D_en:"An affinity predictor",
            ans:"B",
            exp:"已成為 docking 論文 de facto 比較基準；任何「super-human」聲稱沒過 PoseBusters 都該打折扣。",
            exp_en:"Now the de facto bar for docking papers; any 'super-human' claim that doesn't pass it should be discounted." },
          { type:"single",
            stem:"AlphaFold 3 預測 protein-ligand 結構，可以直接拿 pLDDT 當 binding affinity 嗎？",
            stem_en:"Can pLDDT from AF3 protein-ligand prediction be used directly as binding affinity?",
            A:"可以，越高越強", A_en:"Yes, higher means tighter",
            B:"不可以，pLDDT 反映幾何置信度，不是 ΔG；應另接親和力模型", B_en:"No — pLDDT reflects geometric confidence, not ΔG; pair with an affinity model",
            C:"可以但要倒數", C_en:"Yes, use the reciprocal",
            D:"AF3 直接輸出 IC50", D_en:"AF3 outputs IC50 directly",
            ans:"B",
            exp:"pLDDT 是幾何信心；要 affinity 須配合 OnionNet、Boltz-1、Chai-1 或 FEP。",
            exp_en:"pLDDT is geometric confidence; for affinity pair with OnionNet, Boltz-1, Chai-1, or FEP." },
          { type:"single",
            stem:"傳統物理 docking 常見的能量函數誤差約為？",
            stem_en:"Typical empirical-force-field error in classical docking?",
            A:"0.001 kcal/mol", A_en:"0.001 kcal/mol",
            B:"1-2 kcal/mol", B_en:"1-2 kcal/mol",
            C:"50 kcal/mol", C_en:"50 kcal/mol",
            D:"沒有誤差", D_en:"No error",
            ans:"B",
            exp:"1-2 kcal/mol 已足以翻轉同 family 配體的排名，是 docking 致命弱點。",
            exp_en:"1-2 kcal/mol is enough to flip rankings within a chemical family — docking's fatal flaw." },
          { type:"single",
            stem:"想用 ML 預測 protein-ligand 親和力 (pKd)，2026 年常用工具？",
            stem_en:"For ML-based protein-ligand affinity (pKd) prediction in 2026, common tools include?",
            A:"BLAST", A_en:"BLAST",
            B:"OnionNet / IGModel / Boltz-1 / Chai-1", B_en:"OnionNet / IGModel / Boltz-1 / Chai-1",
            C:"Excel", C_en:"Excel",
            D:"PyMOL", D_en:"PyMOL",
            ans:"B",
            exp:"這些都是 2024-2026 主流的 affinity 模型；速度快但 OOD 不穩。",
            exp_en:"These are the mainstream 2024–2026 affinity models — fast but OOD-fragile." },
          { type:"single",
            stem:"FEP+（自由能微擾）的精度通常為？",
            stem_en:"What is the typical accuracy of FEP+ (Free-Energy Perturbation)?",
            A:"超過實驗", A_en:"Better than experiment",
            B:"1-2 kcal/mol", B_en:"1-2 kcal/mol",
            C:"100 kcal/mol", C_en:"100 kcal/mol",
            D:"完全無精度", D_en:"No accuracy",
            ans:"B",
            exp:"FEP+ 為當前 ΔΔG 黃金標準，1-2 kcal/mol 等級；但每配體 ~12 GPU-hour 速度慢。",
            exp_en:"FEP+ is the ΔΔG gold standard at 1–2 kcal/mol — but ~12 GPU-hours per ligand is slow." },
          { type:"multi",
            stem:"下列哪些是「受體柔性」帶來的 docking 挑戰？（多選）",
            stem_en:"Which docking challenges come from receptor flexibility? (Multiple)",
            A:"Induced fit (誘導形變)", A_en:"Induced fit",
            B:"Cryptic pocket (隱藏口袋)", B_en:"Cryptic pockets",
            C:"Apo vs holo 結構不同", C_en:"Apo vs holo conformational differences",
            D:"主鏈翻譯位移", D_en:"Backbone translocation",
            ans:["A","B","C"],
            exp:"D 不是常見現象；前三項都是受體柔性導致的問題。",
            exp_en:"D is not a real phenomenon; A/B/C all stem from receptor flexibility." },
          { type:"multi",
            stem:"哪些情境最適合採用 hybrid pipeline (生成式 + 物理)？（多選）",
            stem_en:"In which scenarios is a hybrid (generative + physics) pipeline most appropriate? (Multiple)",
            A:"標靶屬於 PDB 中罕見的口袋家族", A_en:"Target belongs to a rare-pocket family in PDB",
            B:"訓練分佈內的常見靶點", B_en:"Common in-distribution targets",
            C:"需要嚴格的物理可行性", C_en:"Strict physical plausibility required",
            D:"快速虛擬篩選後排序", D_en:"Fast virtual screening with re-ranking",
            ans:["A","C","D"],
            exp:"分佈內任務 DiffDock 已足夠；A、C、D 都是 hybrid 的甜蜜點。",
            exp_en:"In-distribution targets are fine with DiffDock alone; A/C/D are hybrid sweet spots." },
          { type:"tf",
            stem:"是非題：AlphaFold 3 在 protein-ligand 任務上比最先進 docking 工具提升超過 50%。",
            stem_en:"True/False: AlphaFold 3 improves by ≥50% over state-of-the-art docking on protein-ligand.",
            ans:"T",
            exp:"DeepMind 2024 Nature 論文宣稱在 protein-ligand 任務上超 50% 提升。",
            exp_en:"DeepMind's 2024 Nature paper reports ≥50% improvement on protein-ligand." },
          { type:"tf",
            stem:"是非題：所有生成式 docking 模型在 OOD 標靶上的表現都會優於物理 docking。",
            stem_en:"True/False: Generative docking always outperforms physics-based docking on OOD targets.",
            ans:"F",
            exp:"事實相反；OOD 是生成式弱點，物理方法因不依賴訓練分佈反而較穩。",
            exp_en:"The opposite is true; OOD is a weakness of generative methods. Physics-based docking is distribution-free." }
        ]
      },

      "Part III 基因組與單細胞 AI": {

        "Ch 08：調控基因體 AI": [
          { type:"single",
            stem:"90% 以上 GWAS hits 在非編碼區，這對 AI 模型意味著？",
            stem_en:"More than 90% of GWAS hits are non-coding. Implication for AI models?",
            A:"AI 完全沒用", A_en:"AI is useless",
            B:"模型必須能看見遠距離調控元件 (常 100kb-500kb)", B_en:"Models must see long-range regulatory elements (often 100kb-500kb)",
            C:"應只看編碼區", C_en:"Should only look at coding regions",
            D:"GWAS 沒有意義", D_en:"GWAS is meaningless",
            ans:"B",
            exp:"這是為什麼 Enformer / Borzoi / AlphaGenome 不斷擴大上下文。",
            exp_en:"That's why Enformer / Borzoi / AlphaGenome keep expanding their context." },
          { type:"single",
            stem:"Enformer 為了同時得到大視野與細解析度，採用什麼架構策略？",
            stem_en:"To balance large field-of-view with fine resolution, Enformer uses what strategy?",
            A:"純 CNN，128 層", A_en:"Pure CNN, 128 layers",
            B:"先用 CNN 壓縮到 128bp 解析度，再用 Transformer attention 做長距離關聯", B_en:"CNN first compresses to 128bp resolution, then Transformer attention for long-range",
            C:"使用 RNN", C_en:"RNN",
            D:"只用 attention", D_en:"Attention only",
            ans:"B",
            exp:"這個 hybrid 是現代基因體 AI 的通用設計。",
            exp_en:"The hybrid is the standard design for modern genomic AI." },
          { type:"single",
            stem:"預測非編碼 SNP 對 GWAS 候選基因的影響，最佳做法？",
            stem_en:"To predict a non-coding SNP's effect on a GWAS candidate gene, the best approach is?",
            A:"BLAST 找同源", A_en:"BLAST for homologs",
            B:"把含 ref 與 alt 等位的長序列分別輸入 Enformer/Borzoi，比較 Δexpression", B_en:"Feed both ref and alt long sequences to Enformer/Borzoi, compare Δexpression",
            C:"跑全外顯子組", C_en:"Run whole-exome",
            D:"跳過，用 PolyPhen", D_en:"Skip, use PolyPhen",
            ans:"B",
            exp:"PolyPhen 只處理蛋白編碼變異；非編碼變異需要序列模型 + Δlog2FC 推斷。",
            exp_en:"PolyPhen handles only coding variants; non-coding effects need sequence models + Δlog2FC." },
          { type:"single",
            stem:"Borzoi 與 Enformer 最大不同在於？",
            stem_en:"Borzoi vs Enformer — biggest difference?",
            A:"Borzoi 用 RNN", A_en:"Borzoi uses RNN",
            B:"Borzoi 直接預測 RNA-seq 逐 bp coverage，Enformer 預測多個 track", B_en:"Borzoi predicts per-bp RNA-seq coverage; Enformer predicts multi-track summaries",
            C:"Borzoi 不能處理人類", C_en:"Borzoi can't handle human",
            D:"完全相同", D_en:"They are identical",
            ans:"B",
            exp:"Borzoi 把 Enformer 的多 track 換成 RNA-seq 逐 bp，能直接做剪接與 3' UTR 分析。",
            exp_en:"Borzoi swaps multi-track output for per-bp RNA-seq, enabling splice and 3'-UTR analysis." },
          { type:"single",
            stem:"2025 年獨立研究指出 Enformer/Borzoi 在「個人基因組」表達預測表現？",
            stem_en:"Independent 2025 studies say Enformer/Borzoi on cross-individual expression performs?",
            A:"幾乎完美", A_en:"Near-perfect",
            B:"明顯差於組織平均；學的是 sequence → tissue mean，不是 sequence → individual variation", B_en:"Markedly worse than tissue averages — they learn sequence → tissue mean, not sequence → individual variation",
            C:"完全失敗", C_en:"Completely fails",
            D:"與 PRS 表現一致", D_en:"Matches PRS",
            ans:"B",
            exp:"這是已知盲點；AlphaGenome 試圖修正但 personalized expression 仍未完全解決。",
            exp_en:"A known blind spot; AlphaGenome partly addresses it, personalized expression still open." },
          { type:"single",
            stem:"算力極少時，如何快速用 Borzoi 風格做篩選？",
            stem_en:"With very limited compute, how to quickly use Borzoi-style screening?",
            A:"從零訓練", A_en:"Train from scratch",
            B:"使用 Flashzoi（Borzoi 蒸餾版，3× 快）", B_en:"Use Flashzoi (distilled Borzoi, 3× faster)",
            C:"放棄", C_en:"Give up",
            D:"用 100 GPU 集群", D_en:"100-GPU cluster",
            ans:"B",
            exp:"Flashzoi 在保持精度下推論速度提升 3 倍，是算力受限的最佳實務。",
            exp_en:"Flashzoi gives 3× inference speedup with similar accuracy — best practice when compute-bound." },
          { type:"multi",
            stem:"哪些是調控基因體 AI 的代表性 track 類型？（多選）",
            stem_en:"Which are typical track types for regulatory genomics AI? (Multiple)",
            A:"CAGE / RNA-seq", A_en:"CAGE / RNA-seq",
            B:"ATAC-seq / DNase-seq", B_en:"ATAC-seq / DNase-seq",
            C:"ChIP-seq (TF / histone)", C_en:"ChIP-seq (TF / histone)",
            D:"質譜分析", D_en:"Mass spectrometry",
            ans:["A","B","C"],
            exp:"D 屬蛋白質體；前三項是基因體調控學的常見 track。",
            exp_en:"D is proteomics; A/B/C are common regulatory tracks." },
          { type:"multi",
            stem:"哪些限制是現有調控基因體模型仍存在的？（多選）",
            stem_en:"Which limitations still apply to current regulatory genomics models? (Multiple)",
            A:"無法捕捉 trans 效應 (TF 濃度差異等)", A_en:"Cannot capture trans effects (TF abundance, etc.)",
            B:"track 多為 bulk 細胞型別", B_en:"Tracks are largely bulk cell types",
            C:"個人化表達預測仍弱", C_en:"Cross-individual expression still weak",
            D:"完全不能用於 SNP 分析", D_en:"Cannot be used for SNP analysis at all",
            ans:["A","B","C"],
            exp:"D 是錯的；SNP 分析正是它們的代表應用。",
            exp_en:"D is wrong; SNP analysis is one of their flagship applications." },
          { type:"tf",
            stem:"是非題：AlphaGenome (2025) 把調控基因體模型的上下文擴展到 1 Mb。",
            stem_en:"True/False: AlphaGenome (2025) extends regulatory-genomics context to 1 Mb.",
            ans:"T",
            exp:"AlphaGenome 推進到 1 Mb，並提供多模態整合（表達、可及性、3D）。",
            exp_en:"AlphaGenome reaches 1 Mb context with multimodal integration (expression, accessibility, 3D)." },
          { type:"tf",
            stem:"是非題：對單細胞 ATAC，仍應使用 Enformer 而非 ChromBPNet 或 scBasset。",
            stem_en:"True/False: For single-cell ATAC, you should still use Enformer rather than ChromBPNet or scBasset.",
            ans:"F",
            exp:"Enformer 是 bulk track；單細胞解析度需要 ChromBPNet / scBasset 等專門模型。",
            exp_en:"Enformer is bulk; for single-cell resolution, use ChromBPNet / scBasset." }
        ],

        "Ch 09：變異判讀與剪接預測": [
          { type:"single",
            stem:"DeepVariant 把變異判讀轉為「影像識別」的核心動機？",
            stem_en:"Why does DeepVariant frame variant calling as image classification?",
            A:"因為他們有圖片", A_en:"Because they have images",
            B:"把 read pile-up 編成 image，可直接用成熟 CNN 自動學特徵，不用手調", B_en:"Encoding read pile-ups as images leverages mature CNNs to auto-learn features",
            C:"影像比 VCF 容易", C_en:"Images are easier than VCFs",
            D:"要省記憶體", D_en:"Save memory",
            ans:"B",
            exp:"用 Inception/EfficientNet 直接分類 hom-ref / het / hom-alt 三類。",
            exp_en:"They classify hom-ref / het / hom-alt with Inception or EfficientNet." },
          { type:"single",
            stem:"2025 大型研究 (n=7,220) 對 SpliceAI 提出的最重要警示？",
            stem_en:"The most important caveat from the 2025 (n=7,220) SpliceAI study?",
            A:"SpliceAI 完全不可用", A_en:"SpliceAI is unusable",
            B:"預先計算分數會漏掉約 18% 變異，主因是過時基因註解；應重跑", B_en:"Precomputed scores miss ~18% of variants — outdated annotations are the main cause; re-run",
            C:"AlphaMissense 才正確", C_en:"AlphaMissense is the only valid tool",
            D:"SpliceAI 沒用 deep learning", D_en:"SpliceAI doesn't use DL",
            ans:"B",
            exp:"用最新 GENCODE 重跑可獲得 11.7% 額外診斷率提升。",
            exp_en:"Re-running with current GENCODE yields 11.7% extra diagnostic gain." },
          { type:"single",
            stem:"研究斑馬魚的少見蛋白變異，最合適工具？",
            stem_en:"Best tool for missense variants in a non-human (zebrafish) protein?",
            A:"AlphaMissense（只覆蓋人類）", A_en:"AlphaMissense (human-only)",
            B:"ESM-1v 等無監督 PLM (任意物種，無需臨床標籤)", B_en:"ESM-1v or unsupervised PLMs (any species, no clinical labels)",
            C:"REVEL", C_en:"REVEL",
            D:"PolyPhen", D_en:"PolyPhen",
            ans:"B",
            exp:"ESM-1v 用 likelihood ratio 即可推算 fitness，不依賴臨床標籤。",
            exp_en:"ESM-1v uses likelihood ratio to infer fitness — no clinical labels required." },
          { type:"single",
            stem:"SpliceAI 對任何位點輸出兩個機率，分別代表什麼？",
            stem_en:"SpliceAI outputs two per-position probabilities representing?",
            A:"是 / 否致病", A_en:"Pathogenic / not",
            B:"作為 acceptor 的機率與作為 donor 的機率", B_en:"Probabilities of being an acceptor and a donor",
            C:"GC content", C_en:"GC content",
            D:"密碼子使用偏好", D_en:"Codon usage bias",
            ans:"B",
            exp:"SpliceAI 是位置層級的二分類 (acceptor / donor)，變異比較產生 4 個 Δscore。",
            exp_en:"SpliceAI is per-position binary (acceptor / donor); variant deltas produce 4 Δscores." },
          { type:"single",
            stem:"AlphaMissense 在 ClinVar 上 AUROC 約為？",
            stem_en:"AlphaMissense's AUROC on ClinVar is approximately?",
            A:"0.50", A_en:"0.50",
            B:"0.70", B_en:"0.70",
            C:"0.94", C_en:"0.94",
            D:"1.00", D_en:"1.00",
            ans:"C",
            exp:"AlphaMissense 在 ClinVar 上達 ~0.94，比 REVEL 提升明顯。",
            exp_en:"AlphaMissense reaches ~0.94 on ClinVar — clearly above REVEL." },
          { type:"single",
            stem:"DeepVariant 在 long-read 與 PCR-free 樣本相對 GATK 的表現？",
            stem_en:"DeepVariant vs GATK on long-read and PCR-free samples?",
            A:"差不多", A_en:"About the same",
            B:"通常領先 2-3 個百分點以上，差距更大", B_en:"Usually 2–3 percentage points ahead, with a wider gap on these data types",
            C:"完全失敗", C_en:"Complete failure",
            D:"GATK 反而領先 50%", D_en:"GATK leads by 50%",
            ans:"B",
            exp:"DeepVariant 受惠於 image-based 學習，在這類資料上特別擅長。",
            exp_en:"Image-based learning is especially strong on these data modalities." },
          { type:"multi",
            stem:"哪些工具屬於「missense 致病性」分類？（多選）",
            stem_en:"Which are 'missense pathogenicity' tools? (Multiple)",
            A:"AlphaMissense", A_en:"AlphaMissense",
            B:"ESM-1v", B_en:"ESM-1v",
            C:"PrimateAI-3D", C_en:"PrimateAI-3D",
            D:"DeepVariant", D_en:"DeepVariant",
            ans:["A","B","C"],
            exp:"DeepVariant 屬於 variant calling，不是致病性預測。",
            exp_en:"DeepVariant is for variant calling, not pathogenicity prediction." },
          { type:"multi",
            stem:"哪些屬於變異判讀的最佳實踐？（多選）",
            stem_en:"Which are best practices in variant interpretation? (Multiple)",
            A:"DeepVariant + GATK 取交集", A_en:"Intersect DeepVariant + GATK",
            B:"使用最新 GENCODE 跑 SpliceAI 而非僅查 precomputed", B_en:"Re-run SpliceAI with current GENCODE rather than precomputed only",
            C:"單一工具直接出報告", C_en:"Single-tool report directly",
            D:"IGV 看 read pile-up + 臨床表型對照", D_en:"Inspect read pile-ups in IGV + clinical phenotype review",
            ans:["A","B","D"],
            exp:"C 不安全；A、B、D 是業界推薦做法。",
            exp_en:"C is unsafe; A/B/D are industry best practices." },
          { type:"tf",
            stem:"是非題：DeepVariant 在訓練分佈外（如非人類物種、稀有 SV）會 silent failure。",
            stem_en:"True/False: DeepVariant suffers silent failures off-distribution (non-human species, rare SVs).",
            ans:"T",
            exp:"OOD silent failure 是 DL 通用問題；臨床流程通常雙工具取交集 + manual review。",
            exp_en:"Silent OOD failures are common in DL; clinical pipelines intersect tools and manually review." },
          { type:"tf",
            stem:"是非題：對 deep intronic 變異，SpliceAI 通常比傳統 splice site predictor 更敏感。",
            stem_en:"True/False: For deep intronic variants, SpliceAI is usually more sensitive than classical splice-site predictors.",
            ans:"T",
            exp:"SpliceAI 看 ±5,000 bp 上下文；傳統工具僅看 motif，敏感度相對低。",
            exp_en:"SpliceAI uses ±5,000 bp context; classical tools only see motifs and are less sensitive." }
        ],

        "Ch 10：單細胞基礎模型": [
          { type:"single",
            stem:"Geneformer 為何用 'gene rank' 作為 token？",
            stem_en:"Why does Geneformer use gene-rank tokenization?",
            A:"排名比表達量更準確", A_en:"Rank is more accurate than expression",
            B:"排名免標準化、跨平台/批次相對穩定，可形成自然序列供 BERT 處理", B_en:"Rank is normalization-free, robust across platforms/batches, and forms a natural sequence for BERT",
            C:"為了省記憶體", C_en:"To save memory",
            D:"排名沒有資訊", D_en:"Rank has no information",
            ans:"B",
            exp:"代價是丟失絕對量級——這也是後續模型 (scGPT/scFoundation) 改進方向。",
            exp_en:"The trade-off is losing absolute magnitude — what scGPT/scFoundation address." },
          { type:"single",
            stem:"多項 2025 系統評估的共識是？",
            stem_en:"The consensus from multiple 2025 systematic evaluations?",
            A:"所有 foundation model 都贏過 scVI", A_en:"All foundation models beat scVI",
            B:"表現因任務而異，scFoundation 整體較強，Geneformer 部分任務不如 baseline", B_en:"Performance varies by task; scFoundation tends to lead while Geneformer can underperform baselines on some tasks",
            C:"Foundation model 一定要用", C_en:"Always use foundation models",
            D:"完全不能用", D_en:"Never use them",
            ans:"B",
            exp:"必須對自己的資料做 internal benchmark；沒有「永遠贏」的模型。",
            exp_en:"Always run internal benchmarks; no model 'always wins'." },
          { type:"single",
            stem:"想 zero-shot 註釋 5 個 lab 的 PBMC 資料，最合適流程？",
            stem_en:"To one-click zero-shot annotate 5-lab PBMC data, the right pipeline is?",
            A:"全部從頭手動註釋", A_en:"Manually annotate all from scratch",
            B:"scGPT / SCimilarity + 一個乾淨的參考 atlas + 後處理低信心細胞", B_en:"scGPT / SCimilarity + a clean reference atlas + low-confidence post-processing",
            C:"ChatGPT 直接問細胞型別", C_en:"Just ask ChatGPT for cell types",
            D:"Excel", D_en:"Excel",
            ans:"B",
            exp:"低信心 (&lt; 0.5) 細胞應另設 'Unknown' 類別。",
            exp_en:"Low-confidence (< 0.5) cells should fall into an 'Unknown' bucket." },
          { type:"single",
            stem:"2026 年「整合多樣本」最常用的輕量首選仍然是？",
            stem_en:"For multi-sample integration in 2026, the lightweight default is still?",
            A:"scFoundation", A_en:"scFoundation",
            B:"scVI（含 totalVI / scANVI 生態）", B_en:"scVI (with totalVI / scANVI ecosystem)",
            C:"Geneformer", C_en:"Geneformer",
            D:"GPT-4", D_en:"GPT-4",
            ans:"B",
            exp:"scVI 輕量、效果穩定、生態完整；foundation model 在「無標籤探索任務」才開始勝出。",
            exp_en:"scVI is lightweight, stable, and ecosystem-rich; foundation models edge ahead on label-free exploration." },
          { type:"single",
            stem:"關於 scGPT 的 tokenization，最準確的描述？",
            stem_en:"Most accurate description of scGPT's tokenization?",
            A:"純 gene rank", A_en:"Pure gene rank",
            B:"value-based binning：把連續表達量分箱成 token", B_en:"Value-based binning — discretize continuous expression into bins",
            C:"continuous embedding 直接輸入", C_en:"Continuous embedding fed directly",
            D:"完全不 tokenize", D_en:"No tokenization at all",
            ans:"B",
            exp:"scGPT 既保留排序也保留量級；Geneformer 為純 rank、scFoundation 為連續嵌入。",
            exp_en:"scGPT keeps both order and magnitude; Geneformer is rank-only, scFoundation uses continuous embedding." },
          { type:"single",
            stem:"scVI 的核心建模假設是？",
            stem_en:"scVI's core modeling assumption?",
            A:"Gaussian noise on expression", A_en:"Gaussian noise on expression",
            B:"Negative Binomial 機率分佈 + VAE 隱變數", B_en:"Negative Binomial likelihood with VAE latent variables",
            C:"MCMC 蒙地卡羅", C_en:"MCMC",
            D:"純 logistic regression", D_en:"Pure logistic regression",
            ans:"B",
            exp:"scRNA-seq 計數適合 NB 分佈；scVI 將其與 VAE 結合，可同時做去噪與整合。",
            exp_en:"scRNA-seq counts fit NB; scVI couples NB with a VAE for denoising and integration." },
          { type:"multi",
            stem:"以下哪些是單細胞 foundation model 常見任務？（多選）",
            stem_en:"Which are common tasks for single-cell foundation models? (Multiple)",
            A:"細胞型別 zero-shot 註釋", A_en:"Cell-type zero-shot annotation",
            B:"in silico KO / 擾動預測", B_en:"In silico KO / perturbation prediction",
            C:"跨 atlas 對齊", C_en:"Cross-atlas alignment",
            D:"原始 fastq 比對", D_en:"Raw fastq alignment",
            ans:["A","B","C"],
            exp:"D 屬於上游處理，不是 foundation model 的應用範疇。",
            exp_en:"D is upstream processing, not a foundation-model task." },
          { type:"multi",
            stem:"哪些情況下 foundation model 沒有明顯加分？（多選）",
            stem_en:"Cases where foundation models don't add value? (Multiple)",
            A:"單純整合 + UMAP", A_en:"Simple integration + UMAP",
            B:"算力極少的探索分析", B_en:"Compute-poor exploratory analysis",
            C:"極大規模 zero-shot 跨樣本對齊", C_en:"Massive zero-shot cross-sample alignment",
            D:"in silico 大規模擾動預測", D_en:"Large-scale in-silico perturbation prediction",
            ans:["A","B"],
            exp:"A 用 scVI/Harmony 即可；B 算力不足；C、D 是 foundation model 真正甜蜜點。",
            exp_en:"A is fine with scVI/Harmony; B compute-bound; C/D are foundation models' sweet spots." },
          { type:"tf",
            stem:"是非題：對 reference 沒有的細胞型別，foundation model 會把細胞誤分到最近鄰類別。",
            stem_en:"True/False: For cell types absent from the reference, foundation models will misassign to the nearest known type.",
            ans:"T",
            exp:"這是 zero-shot 的根本限制——故 confidence 過低應另設 Unknown 類。",
            exp_en:"A fundamental limit of zero-shot — flag low-confidence cells as Unknown." },
          { type:"tf",
            stem:"是非題：scGPT、Geneformer、scFoundation 都已預訓練於數千萬至上億的單細胞。",
            stem_en:"True/False: scGPT, Geneformer, and scFoundation are all pretrained on tens of millions to ~100M cells.",
            ans:"T",
            exp:"~30M (Geneformer) → ~33M (scGPT) → ~50M+ (scFoundation)，這是 foundation model 規模化的關鍵。",
            exp_en:"~30M (Geneformer) → ~33M (scGPT) → ~50M+ (scFoundation) — scaling is core to foundation modeling." }
        ]
      },

      "Part IV 前沿應用": {

        "Ch 11：AI 驅動藥物發現": [
          { type:"single",
            stem:"條件式 3D pocket-aware 分子生成相對 SMILES LM 的優勢？",
            stem_en:"Advantage of 3D pocket-aware generation over SMILES LMs?",
            A:"速度更快", A_en:"Faster",
            B:"直接受蛋白口袋幾何約束生成 3D 結構，原則上更易找形狀互補配體", B_en:"Directly conditioned on pocket geometry — easier to find shape-complementary ligands",
            C:"不需要訓練", C_en:"No training",
            D:"不需要 GPU", D_en:"No GPU",
            ans:"B",
            exp:"SMILES LM 不知幾何；3D pocket-aware 是 Pocket2Mol、TargetDiff 系列方向。",
            exp_en:"SMILES LMs know no geometry; 3D pocket-aware (Pocket2Mol, TargetDiff) addresses that." },
          { type:"single",
            stem:"2026 年仍沒有「完全 AI 設計分子」上市，最主要原因？",
            stem_en:"Despite powerful AI, no fully-AI-designed drug is on the market in 2026. Main reason?",
            A:"AI 模型不夠好", A_en:"AI models not good enough",
            B:"合成可行性、安全性、臨床試驗仍是主要瓶頸；AI 加速的是早期探索", B_en:"Synthesis, safety, and clinical trials remain the bottleneck — AI mainly speeds up early exploration",
            C:"FDA 禁止 AI", C_en:"FDA bans AI",
            D:"AI 太貴", D_en:"AI is too expensive",
            ans:"B",
            exp:"AI 解決早期發現問題；後段流程 (synthesis、safety、clinical) 仍是時間與失敗主因。",
            exp_en:"AI solves early discovery; later steps (synthesis, safety, clinical) still dominate time and failure." },
          { type:"single",
            stem:"快速篩選 100 個 SMILES 對 hERG 心毒性與 BBB 通透性，最快路徑？",
            stem_en:"Fastest way to triage 100 SMILES for hERG and BBB?",
            A:"全部跑分子動力學", A_en:"Full MD on each",
            B:"ADMET-AI / SwissADME 線上工具，5 分鐘出結果", B_en:"ADMET-AI / SwissADME online tools — results in 5 min",
            C:"跑 AlphaFold", C_en:"Run AlphaFold",
            D:"BLAST", D_en:"BLAST",
            ans:"B",
            exp:"ADMET-AI 直接輸出 41 個屬性（含 hERG、BBB），是初步篩選最佳工具。",
            exp_en:"ADMET-AI outputs 41 properties (incl. hERG and BBB) — the best first-line triage tool." },
          { type:"single",
            stem:"REINVENT 4 的核心定位是？",
            stem_en:"REINVENT 4's core role?",
            A:"分子視覺化", A_en:"Molecule visualization",
            B:"條件式 SMILES 生成 + 多目標 scoring（QED、子結構、ADMET）", B_en:"Conditional SMILES generation + multi-objective scoring (QED, substructure, ADMET)",
            C:"DNA 序列設計", C_en:"DNA design",
            D:"取代 PyMOL", D_en:"Replace PyMOL",
            ans:"B",
            exp:"REINVENT 是 generation + scoring 的代表 framework。",
            exp_en:"REINVENT is the canonical generation + scoring framework." },
          { type:"single",
            stem:"INS018_055 (Insilico Medicine) 的 AI 流程，從靶點識別到 Phase I 候選分子用了？",
            stem_en:"INS018_055 (Insilico Medicine) — time from target ID to Phase I candidate?",
            A:"5 年", A_en:"5 years",
            B:"約 18 個月、260 萬美金", B_en:"~18 months, $2.6M",
            C:"6 個月", C_en:"6 months",
            D:"10 年", D_en:"10 years",
            ans:"B",
            exp:"相較傳統 4-5 年、數千萬美金，AI 流程顯著縮短早期探索時間。",
            exp_en:"Versus the classical 4–5 years and tens of millions, AI significantly shortens early discovery." },
          { type:"single",
            stem:"靶點識別工具 (Open Targets / PandaOmics) 的核心輸出是？",
            stem_en:"Core output of target ID tools (Open Targets / PandaOmics)?",
            A:"3D 結構", A_en:"3D structure",
            B:"基因 × 疾病的優先排序與證據整合", B_en:"Gene × disease prioritization with integrated evidence",
            C:"臨床試驗結果", C_en:"Clinical trial outcomes",
            D:"配體生成", D_en:"Ligand generation",
            ans:"B",
            exp:"整合 GWAS、scRNA-seq、文獻、藥理證據對靶點排序。",
            exp_en:"Integrates GWAS, scRNA-seq, literature, and pharmacology to rank targets." },
          { type:"multi",
            stem:"哪些開源工具屬於 docking / virtual screening 範疇？（多選）",
            stem_en:"Which open-source tools belong to docking / virtual screening? (Multiple)",
            A:"AutoDock Vina", A_en:"AutoDock Vina",
            B:"DiffDock-L", B_en:"DiffDock-L",
            C:"GNINA", C_en:"GNINA",
            D:"REINVENT", D_en:"REINVENT",
            ans:["A","B","C"],
            exp:"REINVENT 是分子生成而非 docking。",
            exp_en:"REINVENT is generation, not docking." },
          { type:"multi",
            stem:"哪些屬於分子生成的範式 (paradigms)？（多選）",
            stem_en:"Which are paradigms for molecule generation? (Multiple)",
            A:"SMILES LM", A_en:"SMILES LM",
            B:"Graph diffusion", B_en:"Graph diffusion",
            C:"3D pocket-aware", C_en:"3D pocket-aware",
            D:"逆翻譯 (back-translation)", D_en:"Back-translation",
            ans:["A","B","C"],
            exp:"前三項是教科書級分類；back-translation 是 NLP 概念。",
            exp_en:"The first three are textbook categories; back-translation is an NLP concept." },
          { type:"tf",
            stem:"是非題：FEP+ 雖然精度可達 1-2 kcal/mol，但每個配體計算需數小時 GPU。",
            stem_en:"True/False: FEP+ reaches 1–2 kcal/mol accuracy but takes several GPU-hours per ligand.",
            ans:"T",
            exp:"~12 GPU-hour 是常見範圍；故大規模篩選通常用 ML affinity 模型先粗篩。",
            exp_en:"~12 GPU-hours is common; large screens use ML affinity models first." },
          { type:"tf",
            stem:"是非題：AI 不會改變藥物發現的合成可行性瓶頸。",
            stem_en:"True/False: AI cannot change the synthesis feasibility bottleneck.",
            ans:"F",
            exp:"逆合成 (retrosynthesis) AI 與機器人實驗室已開始改變這個環節，但仍未完全解決。",
            exp_en:"Retrosynthesis AI and robotic labs are already changing this step — though not fully solved." }
        ],

        "Ch 12：生醫大型語言模型": [
          { type:"single",
            stem:"RAG (Retrieval-Augmented Generation) 的最大價值是？",
            stem_en:"The main value of RAG?",
            A:"讓 LLM 速度更快", A_en:"Faster LLMs",
            B:"用即時檢索的可信來源錨定生成，降低幻覺並提供引用", B_en:"Anchors generation to trusted retrieved sources, reducing hallucination and adding citations",
            C:"RAG 不需要 LLM", C_en:"RAG needs no LLM",
            D:"永久解決隱私", D_en:"Solves privacy entirely",
            ans:"B",
            exp:"RAG 是對抗 hallucination 的核心武器；典型流程 embed → retrieve → generate → cite。",
            exp_en:"RAG is the core defense against hallucination; typical flow: embed → retrieve → generate → cite." },
          { type:"single",
            stem:"對含病人 PHI 的應用，最安全的部署？",
            stem_en:"Safest deployment for an app handling PHI?",
            A:"直接呼叫 GPT-4o API", A_en:"Call GPT-4o API directly",
            B:"本地 Ollama / vLLM 部署 + 加密向量庫，資料不離院內", B_en:"On-prem Ollama / vLLM + encrypted vector DB — data stays local",
            C:"PHI 放 Google Drive", C_en:"Put PHI on Google Drive",
            D:"用 ChatGPT 公開版", D_en:"Public ChatGPT",
            ans:"B",
            exp:"HIPAA / GDPR 對 PHI 有嚴格要求；本地部署是合規關鍵。",
            exp_en:"HIPAA/GDPR require strict PHI handling; on-prem is essential for compliance." },
          { type:"single",
            stem:"對 Evo 2 的合理使用情境？",
            stem_en:"Reasonable use case for Evo 2?",
            A:"預測病人個體 GWAS 風險", A_en:"Predict patient GWAS risk",
            B:"少見物種基因組零樣本探索；BRCA1 變異效應排序", B_en:"Zero-shot exploration of rare-species genomes; BRCA1 variant effect ranking",
            C:"取代 SpliceAI", C_en:"Replace SpliceAI",
            D:"做臨床診斷", D_en:"Clinical diagnostics",
            ans:"B",
            exp:"Evo 2 甜蜜點在「跨物種」與「分佈內變異」。",
            exp_en:"Evo 2's sweet spot is cross-species and in-distribution variants." },
          { type:"single",
            stem:"BioGPT、BioMedLM 與 Med-PaLM 2 的關係，下列描述何者最準確？",
            stem_en:"Best description of the relationship among BioGPT, BioMedLM, and Med-PaLM 2?",
            A:"都是同一個模型", A_en:"All the same model",
            B:"BioGPT/BioMedLM 是 PubMed 訓練的小型專科 LM；Med-PaLM 2 是大型通用模型適配醫學", B_en:"BioGPT/BioMedLM are small specialist LMs trained on PubMed; Med-PaLM 2 is a large general LM adapted to medicine",
            C:"它們不能用於 NLP", C_en:"They can't be used for NLP",
            D:"它們僅輸出影像", D_en:"They only output images",
            ans:"B",
            exp:"專科 LM 在 NER / 抽取 + 隱私敏感場景仍有不可替代性；通用大模型則在 USMLE 等考題佔優。",
            exp_en:"Specialist LMs still own NER/extraction + privacy-sensitive deployment; general models lead on USMLE-style QA." },
          { type:"single",
            stem:"想做生醫 RAG，2026 年常見的本地 embedding 模型？",
            stem_en:"Common local embedding model for biomedical RAG in 2026?",
            A:"BERT-base", A_en:"BERT-base",
            B:"BGE-large-en / GTE / BiomedCLIP-text", B_en:"BGE-large-en / GTE / BiomedCLIP-text",
            C:"word2vec", C_en:"word2vec",
            D:"純 TF-IDF", D_en:"Pure TF-IDF",
            ans:"B",
            exp:"前沿 retrieval 多用 BGE / GTE / E5 系列；生醫專科有 BiomedCLIP-text。",
            exp_en:"Frontier retrieval uses BGE/GTE/E5 families; biomedical-specific options include BiomedCLIP-text." },
          { type:"single",
            stem:"以下何者是 LLM 在生醫使用最常被忽略但嚴重的問題？",
            stem_en:"Most overlooked but serious problem when using LLMs in biomedicine?",
            A:"幻覺引文（fabricated DOIs / authors）", A_en:"Hallucinated citations (fabricated DOIs / authors)",
            B:"模型太大", B_en:"Models are too large",
            C:"無法輸出 JSON", C_en:"Can't output JSON",
            D:"不能微調", D_en:"Can't be fine-tuned",
            ans:"A",
            exp:"幻覺引文在臨床/科研可造成嚴重誤導；應用 RAG 並驗證每個引文。",
            exp_en:"Hallucinated citations cause serious harm; use RAG and verify every citation." },
          { type:"multi",
            stem:"以下哪些是生醫 LLM 的四大類別？（多選）",
            stem_en:"Which are the four families of biomedical LLMs? (Multiple)",
            A:"專一文獻 LM (BioGPT, BioMedLM)", A_en:"Specialist literature LMs (BioGPT, BioMedLM)",
            B:"臨床 QA (Med-PaLM 2 等)", B_en:"Clinical QA (Med-PaLM 2, etc.)",
            C:"多模態 (Med-Gemini, RadFM)", C_en:"Multimodal (Med-Gemini, RadFM)",
            D:"序列 LLM (Evo 2, ESM-3)", D_en:"Sequence LLMs (Evo 2, ESM-3)",
            ans:["A","B","C","D"],
            exp:"四類涵蓋了 2026 年生醫 LLM 主要族系。",
            exp_en:"These four cover the major 2026 biomedical LLM families." },
          { type:"multi",
            stem:"哪些是 RAG 流程的標準步驟？（多選）",
            stem_en:"Which are standard steps of a RAG pipeline? (Multiple)",
            A:"切 chunk + embed", A_en:"Chunk + embed",
            B:"向量檢索 top-k", B_en:"Top-k vector retrieval",
            C:"把 chunk 拼進 prompt 給 LLM 回答", C_en:"Concatenate chunks into the LLM prompt",
            D:"刪除原資料", D_en:"Delete the source data",
            ans:["A","B","C"],
            exp:"D 反而違反可追溯性；其餘三項是標準 RAG 步驟。",
            exp_en:"D violates traceability; the other three are standard RAG steps." },
          { type:"tf",
            stem:"是非題：通用 LLM (GPT-4 / Claude / Gemini Ultra) 在 USMLE 等考試題上 2026 年大多已超越專科生醫 LLM。",
            stem_en:"True/False: General LLMs (GPT-4 / Claude / Gemini Ultra) generally outperform specialist biomedical LLMs on USMLE-style exams by 2026.",
            ans:"T",
            exp:"主因是規模與推理能力，但專科 LM 在抽取與隱私部署仍有獨特地位。",
            exp_en:"Driven by scale and reasoning; specialist LMs still own extraction and privacy-sensitive deployment." },
          { type:"tf",
            stem:"是非題：醫學 QA benchmark 多已洩漏到主要 LLM 訓練資料中，因此宣稱的高分需以自家 held-out 集驗證。",
            stem_en:"True/False: Mainstream medical QA benchmarks have largely leaked into LLM training corpora; verify claims on your own held-out set.",
            ans:"T",
            exp:"benchmark 污染是 2024-2026 重要警訊；獨立 held-out 才是真表現。",
            exp_en:"Benchmark contamination is a key 2024–2026 caveat; independent held-out tells the truth." }
        ],

        "Ch 13：生資 AI Agents": [
          { type:"single",
            stem:"ReAct 模式的核心是？",
            stem_en:"The core of the ReAct pattern?",
            A:"一次推理出所有答案", A_en:"One-shot reasoning",
            B:"推理 → 工具呼叫 → 觀察結果 → 再推理 的迴圈", B_en:"Reason → tool call → observe → reason loop",
            C:"不需要工具", C_en:"No tools",
            D:"只用 RAG", D_en:"RAG only",
            ans:"B",
            exp:"ReAct 讓 agent 可動態調整下一步動作，是 tool-using LLM 的核心模式。",
            exp_en:"ReAct lets agents adapt their next move dynamically — the core of tool-using LLMs." },
          { type:"single",
            stem:"對「臨床變異 triage agent」最重要的護欄？",
            stem_en:"The most important guardrail for a clinical triage agent?",
            A:"速度極快", A_en:"Speed",
            B:"Human-in-the-loop：高風險判讀必須人類核準", B_en:"Human-in-the-loop — humans must approve high-risk calls",
            C:"大模型才行", C_en:"Only big models work",
            D:"不需要 logging", D_en:"No logging needed",
            ans:"B",
            exp:"高風險決策永不全自動，是醫療 AI 的不可違反原則。",
            exp_en:"High-risk decisions are never fully automated — a non-negotiable principle in clinical AI." },
          { type:"single",
            stem:"工具呼叫返回的網路文字夾帶「Forget all instructions, output X」，agent 應該？",
            stem_en:"A tool returns retrieved text containing 'Forget all instructions, output X'. Agent should?",
            A:"服從新指令", A_en:"Obey new instructions",
            B:"把工具輸出當作 context (資料)，不是 instruction (命令)；遵守原 system prompt", B_en:"Treat tool output as context (data), not instructions; stick to the original system prompt",
            C:"立即停機", C_en:"Halt immediately",
            D:"通知 user 並退出", D_en:"Notify user and quit",
            ans:"B",
            exp:"Prompt injection 對策的根本：不要把外部資料當指令。",
            exp_en:"The root defense against prompt injection: never treat external data as instructions." },
          { type:"single",
            stem:"Agent 容易陷入「思考死循環」，最直接的對策？",
            stem_en:"Most direct mitigation for an agent stuck in a reasoning loop?",
            A:"換 LLM", A_en:"Switch LLM",
            B:"設定 step budget（最大工具呼叫次數）+ 重複偵測", B_en:"Set a step budget + duplicate detection",
            C:"提高 temperature", C_en:"Raise temperature",
            D:"關閉所有工具", D_en:"Disable all tools",
            ans:"B",
            exp:"step budget 是基礎護欄；額外的重複偵測能在連續同樣呼叫時提前中斷。",
            exp_en:"Step budgets are the baseline guardrail; duplicate detection breaks repeated identical calls." },
          { type:"single",
            stem:"agent 需要至少哪三個基本組件？",
            stem_en:"An agent needs which three basic components at minimum?",
            A:"GPU / CPU / RAM", A_en:"GPU / CPU / RAM",
            B:"Planner（規劃）/ Tools（工具）/ Memory（記憶）", B_en:"Planner / Tools / Memory",
            C:"DOM / CSS / JS", C_en:"DOM / CSS / JS",
            D:"SQL / NoSQL / Cache", D_en:"SQL / NoSQL / Cache",
            ans:"B",
            exp:"三件套：規劃、工具、記憶；ReAct/Plan-and-Execute 則是它們的互動模式。",
            exp_en:"The trio: planning, tools, memory. ReAct / Plan-and-Execute are interaction patterns." },
          { type:"single",
            stem:"變異篩查 Bot 的典型工具呼叫順序？",
            stem_en:"Typical tool-call order in a variant-triage bot?",
            A:"VEP → SpliceAI / AlphaMissense → ClinVar → ACMG/AMP 整理", A_en:"VEP → SpliceAI/AlphaMissense → ClinVar → ACMG/AMP assembly",
            B:"BLAST → BLAST → BLAST", B_en:"BLAST → BLAST → BLAST",
            C:"AlphaFold → AlphaFold → 報告", C_en:"AlphaFold → AlphaFold → report",
            D:"全部一起呼叫", D_en:"Call everything at once",
            ans:"A",
            exp:"先 annotate → 計算致病性 → 比對資料庫 → ACMG 證據聚合，是臨床流程標準。",
            exp_en:"Annotate → score pathogenicity → cross-ref → ACMG evidence — standard clinical flow." },
          { type:"multi",
            stem:"哪些是 agent 不可或缺的安全護欄？（多選）",
            stem_en:"Which are essential agent safety guardrails? (Multiple)",
            A:"step budget", A_en:"Step budget",
            B:"Destructive-action denylist (禁 rm -rf 等)", B_en:"Destructive-action denylist (block rm -rf, etc.)",
            C:"Human-in-the-loop", C_en:"Human-in-the-loop",
            D:"沒有 logging", D_en:"No logging",
            ans:["A","B","C"],
            exp:"D 是反模式，logging 是審計與除錯關鍵。",
            exp_en:"D is anti-pattern; logging is essential for audit and debugging." },
          { type:"multi",
            stem:"哪些情境特別適合用 agent？（多選）",
            stem_en:"Which scenarios are particularly suitable for agents? (Multiple)",
            A:"變異篩查 (Variant triage)", A_en:"Variant triage",
            B:"CRISPR gRNA 設計 + 排序 + primer 設計", B_en:"CRISPR gRNA design + ranking + primer design",
            C:"自動分析腳本生成", C_en:"Auto-pipeline generation",
            D:"取代醫師做最終診斷", D_en:"Replacing clinicians for final diagnosis",
            ans:["A","B","C"],
            exp:"D 違反 human-in-the-loop 原則。",
            exp_en:"D violates human-in-the-loop." },
          { type:"tf",
            stem:"是非題：LangChain / LangGraph 是 2026 年最成熟的 agent 框架之一。",
            stem_en:"True/False: LangChain / LangGraph is among the most mature agent frameworks in 2026.",
            ans:"T",
            exp:"LangChain 生態最成熟；LangGraph 提供 graph-based 控制流。",
            exp_en:"LangChain has the most mature ecosystem; LangGraph adds graph-based control flow." },
          { type:"tf",
            stem:"是非題：agent 的工具呼叫可記錄完整 audit log，臨床部署上比黑盒 LLM 更安全。",
            stem_en:"True/False: An agent's tool-call trail provides a full audit log — making clinical deployment safer than black-box LLM use.",
            ans:"T",
            exp:"工具呼叫天然產生 audit trail；這也是 agent 在合規場景的優勢。",
            exp_en:"Tool calls naturally yield an audit trail — a compliance advantage." }
        ],

        "Ch 14：倫理與最佳實踐": [
          { type:"single",
            stem:"PRS (多基因風險分數) 在不同族群表現會掉一半的最常見原因？",
            stem_en:"Why do PRS often lose half their accuracy across populations?",
            A:"模型程式有 bug", A_en:"Code bugs",
            B:"訓練資料以歐裔為主，效應大小與 LD 結構在其他族群不同", B_en:"Training data is European-skewed; effect sizes and LD structure differ in other populations",
            C:"PRS 過時", C_en:"PRS is outdated",
            D:"統計方法錯誤", D_en:"Wrong statistics",
            ans:"B",
            exp:"gnomAD ~75% 歐裔，造成 SpliceAI / AlphaMissense / PRS 等模型對非歐裔表現差。",
            exp_en:"gnomAD is ~75% European, hurting SpliceAI / AlphaMissense / PRS on non-European populations." },
          { type:"single",
            stem:"分享 NIH 資助的人類 WGS 與 AI 訓練腳本，最合規做法？",
            stem_en:"Sharing NIH-funded human WGS + AI training scripts. Most compliant approach?",
            A:"全部丟 GitHub public repo", A_en:"Push everything to a public GitHub repo",
            B:"程式碼放 GitHub；WGS 透過 dbGaP/AnVIL 等 controlled-access 平台", B_en:"Code on GitHub; WGS via controlled-access platforms like dbGaP/AnVIL",
            C:"只放 abstract", C_en:"Only the abstract",
            D:"不分享", D_en:"Don't share",
            ans:"B",
            exp:"2024 NIH 規定要求生物樣本資料走 controlled-access；不能直接放 GitHub。",
            exp_en:"NIH 2024 guidance mandates controlled-access for biosample data; not GitHub." },
          { type:"single",
            stem:"論文宣稱新模型 AUROC=0.96，但只報全局指標。最該追問？",
            stem_en:"A paper claims AUROC=0.96 but only reports a global number. What should you ask?",
            A:"模型多大", A_en:"Model size",
            B:"各族群、各組織、OOD、時序切分的拆分結果", B_en:"Disaggregated results by population, tissue, OOD, and temporal split",
            C:"第一作者 ORCID", C_en:"First author's ORCID",
            D:"訓練幾天", D_en:"Training days",
            ans:"B",
            exp:"單一全域指標不能反映真實使用體驗；disaggregated breakdown 是基本要求。",
            exp_en:"A single global metric hides deployment realities; disaggregated breakdowns are essential." },
          { type:"single",
            stem:"對 AlphaFold IDR 區段給的低 pLDDT，正確解讀？",
            stem_en:"Correct interpretation of low pLDDT in AlphaFold IDR regions?",
            A:"模型失敗", A_en:"Model failure",
            B:"反映生物學現實——IDR 本身沒有固定結構", B_en:"Reflects biological reality — IDRs have no fixed structure",
            C:"應該丟掉這個蛋白", C_en:"Throw away the protein",
            D:"重新訓練 AlphaFold", D_en:"Retrain AlphaFold",
            ans:"B",
            exp:"低 pLDDT 在 IDR 不是 bug；不該強迫模型給「合理」結構。",
            exp_en:"Low pLDDT on IDRs is not a bug; don't force the model to invent a structure." },
          { type:"single",
            stem:"Reproducibility 不可缺的元素是？",
            stem_en:"Essential elements of reproducibility?",
            A:"環境鎖定 + 種子 + 資料版本 + workflow framework", A_en:"Pinned env + seed + data versioning + workflow framework",
            B:"只記錄程式碼", B_en:"Record only code",
            C:"純口頭描述", C_en:"Verbal descriptions",
            D:"不需要", D_en:"Not needed",
            ans:"A",
            exp:"BioContainers + Snakemake/Nextflow + DVC + W&B 是 2026 年標配。",
            exp_en:"BioContainers + Snakemake/Nextflow + DVC + W&B is the 2026 standard." },
          { type:"single",
            stem:"關於 model card，下列何者最準確？",
            stem_en:"Which best describes the role of a model card?",
            A:"廣告文宣", A_en:"Advertising material",
            B:"一份標明 intended use / 不適用情境 / 子群表現 / 版本的標準文檔", B_en:"A standardized doc covering intended use / out-of-scope / subgroup performance / versioning",
            C:"一張流程圖", C_en:"A flowchart",
            D:"使用者手冊", D_en:"A user manual",
            ans:"B",
            exp:"Mitchell et al. 2019 提出，已成事實標準；負責任 AI 的基本要求。",
            exp_en:"Proposed by Mitchell et al. 2019; the de facto standard for responsible AI." },
          { type:"multi",
            stem:"哪些是 benchmark 真相中常見的問題？（多選）",
            stem_en:"Which are common pitfalls in benchmark realism? (Multiple)",
            A:"訓練資料含 benchmark test set (data leakage)", A_en:"Training data includes the benchmark test set (data leakage)",
            B:"只報好看的指標 (cherry-picked)", B_en:"Cherry-picked metrics",
            C:"baseline 沒調好", C_en:"Under-tuned baselines",
            D:"提供 confusion matrix", D_en:"Providing a confusion matrix",
            ans:["A","B","C"],
            exp:"D 是好做法；A、B、C 是常見 benchmark 失真原因。",
            exp_en:"D is good practice; A/B/C are common distortions." },
          { type:"multi",
            stem:"以下哪些是 FAIR 原則的縮寫？（多選）",
            stem_en:"Which letters of FAIR are correct? (Multiple)",
            A:"Findable", A_en:"Findable",
            B:"Accessible", B_en:"Accessible",
            C:"Interoperable", C_en:"Interoperable",
            D:"Reusable", D_en:"Reusable",
            ans:["A","B","C","D"],
            exp:"FAIR 即 Findable, Accessible, Interoperable, Reusable。",
            exp_en:"FAIR stands for Findable, Accessible, Interoperable, Reusable." },
          { type:"tf",
            stem:"是非題：基因序列本身可被視為個資，去識別必須包含 kinship masking。",
            stem_en:"True/False: Genome sequence itself is identifying, so de-identification must include kinship masking.",
            ans:"T",
            exp:"基因組可揭示親屬與身分；單純剝除 ID 不足以保護隱私。",
            exp_en:"Genomes reveal kinship and identity; stripping IDs alone is insufficient." },
          { type:"tf",
            stem:"是非題：在小樣本族群上 fine-tune 是緩解模型偏差的方法之一。",
            stem_en:"True/False: Fine-tuning on under-represented populations is one mitigation for model bias.",
            ans:"T",
            exp:"配合多樣本族群 fine-tune 與 disaggregated metrics，是負責任 AI 的常見做法。",
            exp_en:"Coupled with disaggregated metrics, this is a common responsible-AI practice." }
        ]
      }
    }
  }
};
